<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJKBLBlH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJKBLBlH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJKBLBlH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJKBLBlH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJKBLBlH\App_KernelDevDebugContainer([
    'container.build_hash' => 'JKBLBlH',
    'container.build_id' => '8d6293b9',
    'container.build_time' => 1588157506,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJKBLBlH');
